#!/bin/sh

# Initialize submodules
cd "$HOME"

echo 'Init submodules'
yadm submodule update --recursive --init

# Install Homebrew
system_type=$(uname -s)

if [ "$system_type" = "Darwin" ]; then

  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew"
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  fi

  if [ -f "$HOME/.Brewfile" ]; then
    echo "Installing Homebrew bundle"
    brew bundle --global
  fi

fi

# Install Zinit
if [ ! -d "$HOME/.zinit" ]; then
  echo "Installing Zinit"
  bash -c "$(curl --fail --show-error --silent --location https://raw.githubusercontent.com/zdharma-continuum/zinit/HEAD/scripts/install.sh)"
fi

# Configure iTerm2

if [ "$system_type" = "Darwin" ]; then

  if [ ! -d /Applications/iTerm.app ]; then
    echo "Installing iTerm2"
    brew install iterm2
  fi

  if [ ! -d "$HOME/.iterm2" ]; then
    echo "Setting iTerm preferences"
    defaults write com.googlecode.iterm2 PrefsCustomFolder "$HOME/.iterm2"
  fi
fi

# Configure Doom Emacs
if [ ! -d "$HOME/.emacs.d" ]; then
  echo "Installing Doom"
  git clone --depth 1 https://github.com/hlissner/doom-emacs ~/.emacs.d
  doom install
fi
